version: '3.8'

services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGODB_URI=mongodb+srv://harsheel:harsheel1012@harsheel.kpdvl.mongodb.net/?retryWrites=true&w=majority&appName=harsheel
    depends_on:
      - mongo
  
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
